name: Job Runner

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "00 00 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Cache dependecies Node
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install
        run: yarn install

      - name: Commit
        run: yarn start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
